# Generated by Django 3.2.12 on 2023-10-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231029_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
